### ISSUE TITLE
Establish code style rules

### ISSUE THREAD

**Issue by gajus** [MailOnline/eslint-config-mailonline#1]
I'd like to start an ESLint configuration project for use in MailOnline project. Up to now, @MailOnline/mol-fe team has been using [AirBnb JSCS configuration](https://github.com/jscs-dev/node-jscs/blob/44f9b86eb0757fd4ca05a81a50450c5f1b25c37b/presets/airbnb.json) with some customisations, e.g. https://github.com/MailOnline/mol-fe-contact-form/blob/a015f67f374366ef83c0584912978b62cf0a49f9/.jscsrc#L4-L7.

A simple transition would be to extend from [`eslint-config-airbnb`](https://www.npmjs.com/package/eslint-config-airbnb).

However, there are several things that I do not like about AirBnb style guide:
- Does not enforce [`accessor-pairs`](https://gist.github.com/gajus/1deb7bf1021245d10c9809a106246b5e/revisions?diff=unified#diff-8c0a3562bc108eb2b74f71735c54bf24L3)
- It allows [`arrow-body-style`](https://gist.github.com/gajus/1deb7bf1021245d10c9809a106246b5e/revisions?diff=unified#diff-8c0a3562bc108eb2b74f71735c54bf24L11) no-braces style
- It does not utilise [`babel-eslint`](https://gist.github.com/gajus/1deb7bf1021245d10c9809a106246b5e/revisions?diff=unified#diff-8c0a3562bc108eb2b74f71735c54bf24R24). As a result, not all stage 3 features are supported (e.g. `async/await`)
- It does not enforce [`callback-return`](https://gist.github.com/gajus/1deb7bf1021245d10c9809a106246b5e/revisions?diff=unified#diff-8c0a3562bc108eb2b74f71735c54bf24R24).
- It requires [`comma-dangle`](https://gist.github.com/gajus/1deb7bf1021245d10c9809a106246b5e/revisions?diff=unified#diff-8c0a3562bc108eb2b74f71735c54bf24R47)
- It does not enforce valid `super` invocation using [`constructor-super`](https://gist.github.com/gajus/1deb7bf1021245d10c9809a106246b5e/revisions?diff=unified#diff-8c0a3562bc108eb2b74f71735c54bf24L65)
- It does not not enforce consistent `this` using [`consistent-this`](https://gist.github.com/gajus/1deb7bf1021245d10c9809a106246b5e/revisions?diff=unified#diff-8c0a3562bc108eb2b74f71735c54bf24L64)
- It does not support [flowtype rules](https://gist.github.com/gajus/1deb7bf1021245d10c9809a106246b5e/revisions?diff=unified#diff-8c0a3562bc108eb2b74f71735c54bf24R85)
- It does not enforce a [`func-style`](https://gist.github.com/gajus/1deb7bf1021245d10c9809a106246b5e/revisions?diff=unified#diff-8c0a3562bc108eb2b74f71735c54bf24R100)
- ...

The list keeps going (there are [70+ differences](https://gist.github.com/gajus/1deb7bf1021245d10c9809a106246b5e/revisions?diff=unified#diff-8c0a3562bc108eb2b74f71735c54bf24R100)).

[`eslint-config-canonical`](https://github.com/gajus/eslint-config-canonical) style is a lot more strict than `eslint-config-airbnb`. It has 300+ rules that AirBnb does not bother with. It is the style that I have been maintaining for +1 year and it is used across many public and private projects.

I am proposing that `eslint-config-mailonline` would extend from `eslint-config-canonical` and overwrite only the rules that we disagree about. Having worked on the existing code, the only rule that I can think of is: [`indent`](https://gist.github.com/gajus/1deb7bf1021245d10c9809a106246b5e/revisions?diff=unified#diff-8c0a3562bc108eb2b74f71735c54bf24R180). I prefer 4 spaces, you prefer 2. This can be overwritten in the `eslint-config-mailonline` config.

**Comment by gajus** [comment]
@MailOnline/mol-fe Please review.

**Comment by gajus** [comment]
There are only two rules that I am insistent about:
- [`sort-vars`](https://gist.github.com/gajus/1deb7bf1021245d10c9809a106246b5e/revisions?diff=unified#diff-8c0a3562bc108eb2b74f71735c54bf24R616)
- [`sorting/sort-object-props`](https://gist.github.com/gajus/1deb7bf1021245d10c9809a106246b5e/revisions?diff=unified#diff-8c0a3562bc108eb2b74f71735c54bf24R617)

I can see how someone who is not used to these two rules can be vehemently opposed them, but it is one of the most useful additions to the coding style that I have added over the past 2 years. In combination with [`vars-on-top`](https://gist.github.com/gajus/1deb7bf1021245d10c9809a106246b5e/revisions?diff=unified#diff-8c0a3562bc108eb2b74f71735c54bf24R659), it drastically reduces the noise in the version control.

**Comment by claudiorodriguez** [comment]
I ran `canonical` (installed as global) on a project which already uses `eslint-config-airbnb` and other than indent I think I'm happy with the rules in general. I think we can make the fork and discuss on particular rules there.
I'd suggest everyone trying the rules on their code and weighing in.

Oh yeah, one issue though, I'm getting these errors:

```
║ 1        │ 1        │ error    │ Definition for rule 'no-useless-rename' was not        │ no-useless-rename    ║
║          │          │          │ found                                                  │                      ║
║ 1        │ 1        │ error    │ Definition for rule 'unicode-bom' was not found        │ unicode-bom          ║
║ 1        │ 1        │ error    │ Definition for rule 'object-property-newline' was      │ object-property-     ║
║          │          │          │ not found                                              │ newline              ║
```

**Comment by gajus** [comment]
Please don't confuse [`canonical`](https://github.com/gajus/canonical) with [`eslint-config-canonical`](https://github.com/gajus/eslint-config-canonical).

`canonical` is very experimental and goes beyond validating JavaScript style. It is intended to validate JavaScript, CSS, file names, etc.

[`eslint-config-canonical`](https://github.com/gajus/eslint-config-canonical) contains rules concerning ESLint config.

To test `eslint-config-canonical` (or `eslint-config-mailonline`, which now extends from `eslint-config-canonical` with one exception – indentation), install `eslint-config-canonical` and create `.eslintrc` file with the following contents:

``` json
{
    "extends": "mailonline"
}
```

I am expecting that an avg. code base will report a lot of errors.

**Comment by carpasse** [comment]
> I can see how someone who is not used to these two rules can be vehemently opposed them, but it is one of the most useful additions to the coding style that I have added over the past 2 years. In combination with vars-on-top, it drastically reduces the noise in the version control.

@gajus I have never used 
- sort-vars
- sorting/sort-object-props

I believe variables and object properties should be grouped depending on the context. Can you please explain why sorting the variables on alphabetical order reduces the noise in the version control?

**Comment by gajus** [comment]
> I believe variables and object properties should be grouped depending on the context. Can you please explain why sorting the variables on alphabetical order reduces the noise in the version control?

Because "context" is an arbitrary criteria and alphabetical order is enforced. Simple.

**Comment by carpasse** [comment]
```
function loopOverSomething(items){
  const included = [];
  const excluded = []; 
  let i,len;

  for(i = 0, len = items.length; i < len; i++) {
     const item = items[i];

     if ( mustBeIncluded(item) ) {
       included.push(item);    
     } else {
       excluded.push(item);
     }
  }

  return { included, excluded };
}
```

with `sort-vars` we would have to change the function to:

```
function loopOverSomething(items){
  let i;
  const included = [];
  const excluded = []; 
  let len;

  for(i = 0, len = items.length; i < len; i++) {
     const item = items[i];

     if ( mustBeIncluded(item) ) {
       included.push(item);    
     } else {
       excluded.push(item);
     }
  }

  return { included, excluded };
}
```

correct?

I like to group let and const variables together and keeping the variables that are closely related as close as possible. Would that be possible with `sort-vars` ?

**Comment by gajus** [comment]
> correct?

Incorrect. Thats not what [`sort-vars`](http://eslint.org/docs/rules/sort-vars) do. (`sort-vars` sort variables only in the same declaration block.)

Using all the style requirements from `eslint-config-mailonline`, your code example would look like this:

``` js
const loopOverSomething = (items) => {
  let index,
    itemLength;

  const included = [];
  const excluded = [];

  itemLength = items.length;

  for (index = 0; index < itemLength; index++) {
     const item = items[index];

     if (mustBeIncluded(item)) {
       included.push(item);    
     } else {
       excluded.push(item);
     }
  }

  return {
    excluded,
    included
  };
};
```

> I like to group let and const variables together and keeping the variables that are closely related as close as possible. Would that be possible with sort-vars

The keyword here is "I like". What you like is not necessarily what a developer thats working on this code after you will like. The only way to enforce consistent code style is to remove all cases where developer can make a decision thinking "I like"/"I prefer"/"I am used to" and move to: this is how you do it, it is enforced programmatically.

**Comment by carpasse** [comment]
> The keyword here is "I like". What you like is not necessarily what a developer thats working on this code after you will like. The only way to enforce consistent code style is to remove all cases where developer can make a decision thinking "I like"/"I prefer"/"I am used to" and move to: this is how you do it, it is enforced programmatically.

You are right! 

I now see the value of `sort-vars` and `sorting/sort-object-props` thanks for clarifying it.

**Comment by carlosvillademor** [comment]
Yeah! Something to enforce alphabetical order! I like it! I do it myself. One question though, how would it work with variables in the require section where there are dependencies that you need to require before regardless of their name?

i.e:

```
const b = require('b')
const a = functionThatUsesB(b);
```

**Comment by gajus** [comment]
> One question though, how would it work with variables in the require section where there are dependencies that you need to require before regardless of their name?

`sort-vars` applies only to the variables that are declared in the same block.

``` js
const
    a = require('a'),
    b = require('b');
```

The example you have used is not affected.

**Comment by carlosvillademor** [comment]
Ok, my bad, you mentioned it in another comment above. We do not use multiple variable declaration in one block though.

**Comment by carlosvillademor** [comment]
What is your take on how to order variables in different blocks?

**Comment by gajus** [comment]
> What is your take on how to order variables in different blocks?

It is not possible to enforce that. (Because of the reason you have stated.)

Somewhat related, the import order is important though.

https://gist.github.com/gajus/1deb7bf1021245d10c9809a106246b5e/revisions?diff=unified#diff-8c0a3562bc108eb2b74f71735c54bf24L132

**Comment by claudiorodriguez** [comment]
Retaking this conversation - I'm fine with `eslint-config-mailonline`, I would only change the following:
- Lock version of `eslint-config-canonical` to ensure build predictability (otherwise when said package changes rules around on a patch/minor, a build that previously passed might now fail, even if it locks version of `eslint-config-mailonline` since we're talking about a dep of a dep), and when it is updated, or rules are changed, release a new major for `eslint-config-mailonline`
- Disable `lodash/prefer-lodash-typecheck` (should be project-specific)

**Comment by gajus** [comment]
There have been a few changes to https://github.com/gajus/eslint-config-canonical. Those worth mentioning:
- mocha rules have been separated into separate configuration (https://github.com/gajus/eslint-config-canonical/commit/525b8bef454b689150a8a436103d4ea98e9cc7e5) [they started to throw false positives in ava tests, e.g. "Unexpected use of `return` in a test with callback  mocha/no-return-and-callback"]
- AVA configuration has been added (https://github.com/gajus/eslint-config-canonical/commit/e1f0b59e0c44d3eee19b278f0bf6bc4a06a6c8bd)
- `"promise/no-native"` has been disabled (now inline with eslint-config-mailonline)

**Comment by claudiorodriguez** [comment]
Closing this as team consensus has been reached.
