### ISSUE TITLE
Discussion on specific rules

### ISSUE THREAD

**Issue by claudiorodriguez** [MailOnline/eslint-config-mailonline#3]
Making this issue for discussion on specific rules.

The only one that seems a bit weird to me really is `babel/object-curly-spacing` - it specifically forbids syntax like `{ a: 1, b: 2 }` which is widespread among most major authors and companies and to me makes sense because it makes the code more readable than `{a: 1, b: 2}`. I'm definitely open to hearing arguments.

And two rules that I don't feel strongly about one way or the other but that collide with the style established by the team:

func-style (Expected a function expression)
no-restricted-syntax (Using 'TemplateLiteral' is not allowed)

I understand the rationale behind them but since we currently use template literals and function declarations a lot in our code right now, it might be wise to discuss them.

**Comment by carlosvillademor** [comment]
I'm not a big fan of the space between {}, bug given that seems to be widespread and that clashes with our current setup, I think we should change the babel/object-curly-spacing option.

**Comment by gajus** [comment]
> The only one that seems a bit weird to me really is babel/object-curly-spacing - it specifically forbids syntax like { a: 1, b: 2 } which is widespread among most major authors and companies and to me makes sense because it makes the code more readable than {a: 1, b: 2}. I'm definitely open to hearing arguments.

As far as I can remember the implications, this rule is irrelevant because you are not allowed to have multiple properties on a single line, https://github.com/gajus/eslint-config-canonical/blob/0012b69178974a4536cb4948f0cf28b60305880b/configurations/eslintrc.json#L560-L565.

``` json
"object-property-newline": [
  2,
  {
    "allowMultiplePropertiesPerLine": false
  }
],
```

**Comment by claudiorodriguez** [comment]
Note that I have since changed my view on object curly spacing - I now prefer no spaces.

**Comment by brokenmass** [comment]
this is still relevant if the object has only 1 property `{ a: 5 }` or if you use destructuring.

we should probably just vote for one or the other to solve the issue

**Comment by brokenmass** [comment]
Add a reaction to this message with:
- +1 if you want spaces `{ test: 1 }` 
- -1 if you don't `{test: 1}`

First that gets to 5 wins

**Comment by gajus** [comment]
> Note that I have since changed my view on object curly spacing - I now prefer no spaces.

Style preference is a strange thing. I have used to use 4 spaces before joining MOL and was swearing every time I see 2 space indentation. Now.. I could not go back to 4 spaces (I would consider going to tabs. :-))

**Comment by claudiorodriguez** [comment]
Fortunately, object curly spacing is an AUTOFIX rule so the transition will not be problematic one way or the other.
I'm more worried about how the team feels about stuff like sort-keys which I've come to like but admittedly will take a lot of manual work

**Comment by A0dh** [comment]
I choose no spaces in objects, because spaces are not allowed in arrays ether.

**Comment by brokenmass** [comment]
No spaces won

**Comment by carpasse** [comment]
😔
