### ISSUE TITLE
Problem with version 1.7.13 of eslint-config-canonical

### ISSUE THREAD

**Issue by claudiorodriguez** [MailOnline/eslint-config-mailonline#5]
Hey there. Since you released version `1.7.13` of `eslint-config-canonical`, `eslint-config-mailonline` throws an error. I tried a fresh install on a new project and it throws this:

```
ESLint couldn't find the plugin "eslint-plugin-sorting". This can happen for a couple different reasons:
```

I tried installing that package and in that case it works on the fresh project but in mol-fe-legal-admin it's throwing:

```
TypeError: Cannot read property 'prevName' of null
```

Since 1.7.13 of eslint-config-canonical appears to be a breaking version, can we force 1.7.12 here?

**Comment by gajus** [comment]
Fixed (https://github.com/gajus/eslint-config-canonical/commit/629e186d0edfe6edb2a8700dbbdead5c733ea6a2) in v1.7.14.
